import type { Metadata } from "next"
import { Chicle, Geist, Geist_Mono, JetBrains_Mono, Pixelify_Sans } from "next/font/google"
import "./globals.css"
import { ScreenSize } from "./page.client"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${ geistSans.variable } ${ geistMono.variable } ${ jetbrainsMono.variable } antialiased flex flex-col min-h-screen p-8 pt-10 pb-20 sm:p-20 sm:pt-16 ${ geistSans.className }`}
      >
        <ScreenSize />
        {children}
      </body>
    </html>
  )
}
